Package:
 name: 'kubernetes'
# Keeping this commented out cause the stable commit id used by centOS isn't
# available in any branch in the default remote. We need to wait for the hook
# functionality and or the ability to clone multiple repositories to get this
# yaml in its best shape.
# clone_url: 'https://github.com/kubernetes/kubernetes.git'
# branch: 'release-1.2'
# commit_id: '5cb86ee022267586db386f62781338b0483733b3'
 sources:
   - url:
      src: 'https://github.com/kubernetes/kubernetes/archive/4a3f9c5b19c7ff804cbc1bf37a15c044ca5d2353/kubernetes-4a3f9c5.tar.gz'
      archive: 'kubernetes-4a3f9c5.tar.gz'
 files:
  centos:
   '7.2':
    spec: 'centOS/7.2/kubernetes.spec'
    build_files: 'centOS/7.2/SOURCES'
    download_build_files:
     - 'https://github.com/openshift/origin/archive/ef1caba064de975387860175c3138aad432cf356/origin-ef1caba.tar.gz'
     - 'https://github.com/kubernetes/contrib/archive/18bb93d3509bd13a15639969c8b0ebe39a7f9b50/contrib-18bb93d.tar.gz'
    build_dependencies:
     - golang
